import type { Config } from "tailwindcss";

export default {
  presets: [require("nativewind/preset") as any],
  darkMode: "class",
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        card: "var(--card)",
        ring: "var(--ring)",
        input: "var(--input)",
        muted: "var(--muted)",
        accent: "var(--accent)",
        border: "var(--border)",
        popover: "var(--popover)",
        primary: "var(--primary)",
        sidebar: "var(--sidebar)",
        secondary: "var(--secondary)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        destructive: "var(--destructive)",
        success: "var(--success)",
        warning: "var(--warning)",
        surface: "var(--surface)",
        "surface-elevated": "var(--surface-elevated)",
        "glass-bg": "var(--glass-bg)",
        "sidebar-ring": "var(--sidebar-ring)",
        "sidebar-accent": "var(--sidebar-accent)",
        "sidebar-border": "var(--sidebar-border)",
        "card-foreground": "var(--card-foreground)",
        "sidebar-primary": "var(--sidebar-primary)",
        "muted-foreground": "var(--muted-foreground)",
        "accent-foreground": "var(--accent-foreground)",
        "popover-foreground": "var(--popover-foreground)",
        "primary-foreground": "var(--primary-foreground)",
        "sidebar-foreground": "var(--sidebar-foreground)",
        "secondary-foreground": "var(--secondary-foreground)",
        "destructive-foreground": "var(--destructive-foreground)",
        "success-foreground": "var(--success-foreground)",
        "warning-foreground": "var(--warning-foreground)",
        "sidebar-accent-foreground": "var(--sidebar-accent-foreground)",
        "sidebar-primary-foreground": "var(--sidebar-primary-foreground)",
        "chart-1": "var(--chart-1)",
        "chart-2": "var(--chart-2)",
        "chart-3": "var(--chart-3)",
        "chart-4": "var(--chart-4)",
        "chart-5": "var(--chart-5)",
        "primary-light": "var(--primary-light)",
        "accent-light": "var(--accent-light)",
        "destructive-light": "var(--destructive-light)",
        "success-light": "var(--success-light)",
        "warning-light": "var(--warning-light)",
        "border-light": "var(--border-light)",
        "text-secondary": "var(--text-secondary)",
        "text-tertiary": "var(--text-tertiary)",
        shadow: "var(--shadow)",
      },
      fontFamily: {
        sans: ["Montserrat", "system-ui", "sans-serif"],
        mono: ["Fira Code", "monospace"],
        serif: ["Georgia", "serif"],
      },
      fontSize: {
        display: ["36px", { lineHeight: "44px", fontWeight: "700" }],
        h1: ["28px", { lineHeight: "34px", fontWeight: "700" }],
        h2: ["22px", { lineHeight: "28px", fontWeight: "700" }],
        h3: ["18px", { lineHeight: "24px", fontWeight: "600" }],
        body: ["16px", { lineHeight: "24px" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "500" }],
        label: ["10px", { lineHeight: "14px", fontWeight: "700" }],
        mono: ["14px", { lineHeight: "20px" }],
      },
      borderRadius: {
        DEFAULT: "0.35rem",
      },
    },
  },
  plugins: [],
} satisfies Config;
